In [2]:
import pandas as pd

In [3]:
import seaborn as sns

In [4]:
df = pd.read_csv("/content/diabetes_prediction_dataset (1).csv")

In [5]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [7]:
df["gender"].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [8]:
df["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [9]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(3854)

In [11]:
df1=df.copy()

In [12]:
df1["smoking_history"] = df1["smoking_history"].apply (lambda x :  "not current" if x == "former"  else x)

In [13]:
df1["smoking_history"].unique()

array(['never', 'No Info', 'current', 'not current', 'ever'], dtype=object)

In [14]:
df1.duplicated().sum()

np.int64(3952)

In [15]:
df1.drop_duplicates(inplace = True)

In [16]:
df1.duplicated().sum()

np.int64(0)

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96048 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               96048 non-null  object
 1   age                  96048 non-null  float64
 2   hypertension         96048 non-null  int64
 3   heart_disease        96048 non-null  int64
 4   smoking_history      96048 non-null  object
 5   bmi                  96048 non-null  float64
 6   HbA1c_level          96048 non-null  float64
 7   blood_glucose_level  96048 non-null  int64
 8   diabetes             96048 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 7.3+ MB

In [18]:
#one method
from sklearn.preprocessing import LabelEncoder

L = LabelEncoder()

for i in df1.columns:
    if df1[i].dtype == "object":
        df1[i] = L.fit_transform(df1[i])
        print(df1[i])

0        0
1        0
2        1
3        0
4        1
        ..
99994    0
99996    0
99997    1
99998    0
99999    0
Name: gender, Length: 96048, dtype: int64
0        3
1        0
2        3
3        1
4        1
        ..
99994    0
99996    0
99997    4
99998    3
99999    1
Name: smoking_history, Length: 96048, dtype: int64

In [19]:
#another method
L = LabelEncoder()
for i in df1.select_dtypes(include = ["object"]).columns:
    df1[i].L_fit_transform(df1[i])

In [20]:
df1

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,3,25.19,6.6,140,0
1,0,54.0,0,0,0,27.32,6.6,80,0
2,1,28.0,0,0,3,27.32,5.7,158,0
3,0,36.0,0,0,1,23.45,5.0,155,0
4,1,76.0,1,1,1,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99994,0,36.0,0,0,0,24.60,4.8,145,0
99996,0,2.0,0,0,0,17.37,6.5,100,0
99997,1,66.0,0,0,4,27.83,5.7,155,0
99998,0,24.0,0,0,3,35.42,4.0,100,0
99999,0,57.0,0,0,1,22.43,6.6,90,0

In [21]:
# x is always independent columns
# y is always dependent columns

In [22]:
y = df1["diabetes"]
y

0        0
1        0
2        0
3        0
4        0
        ..
99994    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 96048, dtype: int64

In [23]:
x = df1.drop("diabetes",axis = 1)
x

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,0,80.0,0,1,3,25.19,6.6,140
1,0,54.0,0,0,0,27.32,6.6,80
2,1,28.0,0,0,3,27.32,5.7,158
3,0,36.0,0,0,1,23.45,5.0,155
4,1,76.0,1,1,1,20.14,4.8,155
...,...,...,...,...,...,...,...,...
99994,0,36.0,0,0,0,24.60,4.8,145
99996,0,2.0,0,0,0,17.37,6.5,100
99997,1,66.0,0,0,4,27.83,5.7,155
99998,0,24.0,0,0,3,35.42,4.0,100
99999,0,57.0,0,0,1,22.43,6.6,90

In [24]:
df1["diabetes"].value_counts()

diabetes
0    87566
1     8482
Name: count, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.05)

In [26]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((91245, 8), (4803, 8), (91245,), (4803,))

In [27]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier().fit(x_train,y_train)

In [28]:
import numpy as np

In [29]:
vp = np.array([[1,25,0,0,3,28.4,6.8,220]])

In [30]:
model.predict(vp)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [32]:
du = np.array([[1,25,0,0,3,28.4,4.8,200]])
model.predict(du)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [33]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, ..., 1, 1, 0])

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[4214,  136],
       [ 115,  338]])

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      4350
           1       0.71      0.75      0.73       453

    accuracy                           0.95      4803
   macro avg       0.84      0.86      0.85      4803
weighted avg       0.95      0.95      0.95      4803

In [36]:
import pickle

In [37]:
pickle.dump(model,open("Diabetes.pkl","wb"))